name: Image build and clean old images

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  build-and-push-on-pr-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the github container registry (GCR)
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io/thomascardin
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx

      - name: Build and push (latest)
        id: docker_build_latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/thomascardin/${{ github.event.repository.name }}:${{ github.event.number }}
            ghcr.io/thomascardin/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Refresh Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image digest (latest)
        run: echo ${{ steps.docker_build_latest.outputs.digest }}

  remove-old-image:
    runs-on: ubuntu-latest
    needs: build-and-push-on-pr-merge
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install requests

      - name: Run Python Script
        run: python scripts/remove-old-image.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: ghcr.io/thomascardin
          CONTAINER_NAME: ${{ github.event.repository.name }}
          PR_TAG: ${{ github.event.number }}
          USER: ${{ github.actor }}
          CURRENT_COMMIT: ${{ github.sha }}
